### ISSUE TITLE
SSPX support

### ISSUE THREAD

**Issue by inkognito1100** [steamp0rt/Kerbalism#5]
SSPX support is totally broken: you can't add shielding to inflatable modules in hangar; after enabling habitat on inflatable module pressure drops and living space increases immediately, module starts to consume EC, but animation of extending plays until pressure becomes 101 kPa and only then appears firm-ground bonus; SSPX greenhouses have different masses, but almost same surface, volume and crop sizes, also they consume and produce resources different to Kerbalism greenhouse. Also, there are some minor issues such as written twice habitat surface and volume.
![screenshot287](https://user-images.githubusercontent.com/22282875/39610539-c3c24650-4f59-11e8-8bcb-6af7ad442223.png)
![screenshot289](https://user-images.githubusercontent.com/22282875/39610547-cbe189ae-4f59-11e8-8c14-e3e3a6ae67c8.png)

**Comment by MoreRobustThanYou** [comment]
The greenhouse is easily fixable (crop size is `mass in tons * 1000`)

**Comment by MoreRobustThanYou** [comment]
Also, it's intentional inflatable modules can't have shielding... it's kinda hard to make a lead-lined inflatable thing.

**Comment by inkognito1100** [comment]
I've found where to fix greenhouses, planing to do it tonight. 
But inflatable modules has shielding bar in flight and it is possible to add shielding with ISRU. Gravity rings have great volume, such part without shielding significantly reduces overall shielding of vessel. Shielding in hangar wouldn't be imbalance because shielded inflatable module will weight lots of tons. I think that it will be enough realistic if you imagine a crew who putting lead plates from Kerbin into inflatable module.

**Comment by MoreRobustThanYou** [comment]
I already pushed a greenhouse crop size fix.

**Comment by inkognito1100** [comment]
you didn't fix resources input/output rate and it is still CO2 + fertiliser needed instead of ammonia

**Comment by inkognito1100** [comment]
and by-product must be waste water, not waste

**Comment by MoreRobustThanYou** [comment]
@inkognito1100 fixed in https://github.com/MoreRobustThanYou/Kerbalism/commit/f790f7968c761d57b3f36d6e71324f2cf4ac8c18

**Comment by madman2003** [comment]
@steamp0rt shouldn't this one be closed?
